<?php

use PHPUnit\Framework\TestCase;
require __DIR__ . "\..\php\partition.php"; //dołączenie klasy partition którą testujemy

class partitionTest extends TestCase
{

    protected $partition;

    public  function setUp(): void
    {
        //funkcja ta wykonuje się przed innymi, za każdym wywołaniem innej funkcji:

        //utworzenie przykładowego usera z następującymi danymi:
        $this->partition = new partition(
            1,
            "sample_password",
            "1",
            "www.fooo.bar", //przykładowa strona
            "sample description",
            "sample_login"
        );

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**@test*/
    public function testGetId()
    {
        $this->assertSame(1, $this->partition->getID()); //sprawdzenie czy pobrana z utworzonej zakładki są takie same jak w kodzie
    }

    /**@test*/
    public function testGetWeb_Address()
    {
        $this->assertSame("www.fooo.bar", $this->partition->getWeb_Address()); //sprawdzenie czy pobrana z utworzonej zakładki są takie same jak w kodzie
    }

    /**@test*/
    public function testGetLogin()
    {
        $this->assertSame("sample_login", $this->partition->getLogin()); //sprawdzenie czy pobrana z utworzonej zakładki są takie same jak w kodzie
    }

    /**@test*/
    public function testGetDescription()
    {
        $this->assertSame("sample description", $this->partition->getDescription()); //sprawdzenie czy pobrana z utworzonej zakładki są takie same jak w kodzie
    }

    /**@test*/
    public function testGetId_User()
    {
        $this->assertSame("1", $this->partition->getId_User()); //sprawdzenie czy pobrana z utworzonej zakładki są takie same jak w kodzie
    }

    /**@test*/
    public function testGetPassword()
    {
        $this->assertSame("sample_password", $this->partition->getPassword()); //sprawdzenie czy pobrana z utworzonej zakładki są takie same jak w kodzie
    }
}
