<?php

use PHPUnit\Framework\TestCase;
require __DIR__ . "\..\php\user.php"; //dołączenie klasy user którą testujemy

class userTest extends TestCase
{
    protected $user;
    public  function setUp(): void
    {
        //funkcja ta wykonuje się przed innymi, za każdym wywołaniem innej funkcji:

        //utworzenie przykładowego usera z następującymi danymi:
        $this->user = new user(
          1,
          "loginTest",
          "795d08f0f8b31407e0e5f21a684aac039d5bf8589892f51bd8e1b75b5ac1157d2078fcbdb94d626b079eb066564a2573d6df24673aa6fe08e04fa0c67d765fdf", //zahaszowane hasło "test" - SHA512
        "21393807795f9ecce161", //przykładowa sól
        true
        );

        /*
         c360d7cc0454b121bc4bd276b844090316ff7281aff1c4dc45265d643145d64180029647303513e0b44a4535f5d563e276f6ec104b77f7e0a3cf2edb1c0e901e
        hasło HMAC
         */

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**@test*/
    public function testGetLogin()
    {
        $this->assertSame("loginTest", $this->user->getLogin()); //sprawdzenie czy pobrana z utworzonego użytkownika są takie same jak w kodzie
    }

    /**@test*/
    public function testGetPassword_Hash()
    {
        $this->assertSame("795d08f0f8b31407e0e5f21a684aac039d5bf8589892f51bd8e1b75b5ac1157d2078fcbdb94d626b079eb066564a2573d6df24673aa6fe08e04fa0c67d765fdf", $this->user->getPassword_Hash()); //sprawdzenie czy pobrana z utworzonego użytkownika są takie same jak w kodzie

    }

    /**@test*/
    public function testGetIsPasswordKeptAsHash()
    {
        $this->assertTrue($this->user->getIsPasswordKeptAsHash());
    }


    /**@test*/
    public function testGetSalt()
    {
        $this->assertSame("21393807795f9ecce161", $this->user->getSalt()); //sprawdzenie czy pobrana z utworzonego użytkownika są takie same jak w kodzie
    }

    /**@test*/
    public function testGetId()
    {

        $this->assertSame(1, $this->user->getId());
    }
    /**@test*/
    public function testShowUserInfo()
    {
        $this->assertSame(
            "Id: 1<br>Login: loginTest<br>Password_Hash: 795d08f0f8b31407e0e5f21a684aac039d5bf8589892f51bd8e1b75b5ac1157d2078fcbdb94d626b079eb066564a2573d6df24673aa6fe08e04fa0c67d765fdf<br>Salt: 21393807795f9ecce161<br>isPasswordKeptAsHash: 1<br>",
            "Id: ".$this->user->getId()."<br>"."Login: ".$this->user->getLogin()."<br>"."Password_Hash: ".$this->user->getPassword_Hash()."<br>"."Salt: ".$this->user->getSalt()."<br>"."isPasswordKeptAsHash: ".$this->user->getIsPasswordKeptAsHash()."<br>"
        );
    }

}
